<?php
// Isolated database and in-process provider mock: no external network requests.
putenv('DB_DRIVER=sqlite');putenv('APP_ENV=local');putenv('PAYMENT_DRIVER=demo');putenv('SQLITE_PATH='.__DIR__.'/../storage/unit-'.bin2hex(random_bytes(5)).'.sqlite');
require __DIR__.'/../server/bootstrap.php';require __DIR__.'/../scripts/migrate.php';require __DIR__.'/../server/features.php';require __DIR__.'/../server/payments.php';require __DIR__.'/../server/notifications.php';
$assertions=0;function check(bool $condition,string $message):void{global $assertions;if(!$condition)throw new RuntimeException($message);$assertions++;}
$calls=0;$failProvider=false;
function externalJson(string $url,string $method='GET',array $headers=[],?string $body=null):array{global $calls,$failProvider;$calls++;if($failProvider)throw new RuntimeException('Provedor externo indisponível (HTTP 503).');return ['id'=>'email-mock-'.$calls,'sid'=>'whatsapp-mock-'.$calls];}
$now=date('Y-m-d H:i:s');query('INSERT INTO users(name,email,password_hash,created_at) VALUES(?,?,?,?)',['Unit','unit@example.test',password_hash('ExampleTestOnly!2026',PASSWORD_DEFAULT),$now]);$uid=db()->lastInsertId();query("INSERT INTO businesses(user_id,category_id,plan_id,interest_plan_id,name,description,purpose,neighborhood,address,phone,notification_channel,whatsapp_consent,created_at,status) VALUES(?,7,2,3,'Unit business','Descrição suficiente para teste','','Centro','Rua local','31999999999','both',1,?,'pending')",[$uid,$now]);$bid=(int)db()->lastInsertId();query("INSERT INTO subscriptions(business_id,plan_id,provider_id,billing_type,status,created_at) VALUES(?,2,'sub_unit','PIX','pending',?)",[$bid,$now]);
check(substr(nextMonth('2026-01-31 23:59:59'),0,10)==='2026-02-28','Mês civil em janeiro');check(substr(nextMonth('2028-01-31 23:59:59'),0,10)==='2028-02-29','Ano bissexto');
$p=['id'=>'payment_one','subscription'=>'sub_unit','value'=>75,'dueDate'=>date('Y-m-d'),'paymentDate'=>date('Y-m-d'),'status'=>'RECEIVED'];applyPayment($p);$first=one('SELECT * FROM businesses WHERE id=?',[$bid]);check(isLive($first),'Pagamento ativa acesso');applyPayment($p);check(one('SELECT * FROM businesses WHERE id=?',[$bid])['paid_until']===$first['paid_until'],'Pagamento duplicado não estende acesso');
try{applyPayment(array_merge($p,['id'=>'wrong_amount','value'=>1]));throw new RuntimeException('Valor incorreto aceito');}catch(RuntimeException $e){check($e->getMessage()==='Valor divergente','Recusa valor divergente');}
applyPayment(array_merge($p,['status'=>'REFUNDED']));$ref=one("SELECT * FROM payments WHERE provider_id='payment_one'");check($ref['paid_at']!==null&&$ref['refunded_at']!==null,'Estorno preserva histórico de recebimento');check(!isLive(one('SELECT * FROM businesses WHERE id=?',[$bid])),'Estorno retira acesso pago');
applyPayment(array_merge($p,['id'=>'payment_two']));check(isLive(one('SELECT * FROM businesses WHERE id=?',[$bid])),'Outra cobrança paga permite acesso');applyPayment(array_merge($p,['status'=>'REFUNDED']));check(isLive(one('SELECT * FROM businesses WHERE id=?',[$bid])),'Estorno antigo não apaga outro período pago');
query("UPDATE businesses SET status='suspended' WHERE id=?",[$bid]);applyPayment(array_merge($p,['id'=>'payment_two']));check(!isLive(one('SELECT * FROM businesses WHERE id=?',[$bid])),'Webhook não remove suspensão');query("UPDATE businesses SET status='active' WHERE id=?",[$bid]);
putenv('NOTIFICATION_MODE=automatic');
foreach(['NOTIFICATIONS_ENABLED'=>'true','RESEND_API_KEY'=>'mock','EMAIL_FROM'=>'mock@example.test','TWILIO_ACCOUNT_SID'=>'mock','TWILIO_API_KEY'=>'mock','TWILIO_API_SECRET'=>'mock','TWILIO_WHATSAPP_FROM'=>'whatsapp:+5500000000000','TWILIO_CONTENT_SID'=>'mock']as$k=>$v)putenv($k.'='.$v);
$b=one('SELECT * FROM businesses WHERE id=?',[$bid]);queueNotice($b,'notification-unit','Aviso para teste');queueNotice($b,'notification-unit','Aviso para teste');check((int)one("SELECT COUNT(*) n FROM notifications WHERE dedup_key='notification-unit'")['n']===1,'Avisos deduplicados');$result=runDeliveries();check($result['sent']>=2,'Ambos os canais são enviados por adaptador mock');$before=$calls;runDeliveries();check($calls===$before,'Envio não se repete');
queueNotice($b,'retry-unit','Aviso sujeito a falha');$failProvider=true;runDeliveries();$delivery=one("SELECT d.* FROM deliveries d JOIN notifications n ON n.id=d.notification_id WHERE n.dedup_key='retry-unit' AND d.channel='email'");check($delivery['status']==='retry','E-mail agenda nova tentativa');$wa=one("SELECT d.* FROM deliveries d JOIN notifications n ON n.id=d.notification_id WHERE n.dedup_key='retry-unit' AND d.channel='whatsapp'");check($wa['status']==='uncertain','WhatsApp incerto não duplica');
$failProvider=false;query('UPDATE deliveries SET next_attempt_at=? WHERE id=?',['2020-01-01',$delivery['id']]);runDeliveries();check(one('SELECT status FROM deliveries WHERE id=?',[$delivery['id']])['status']==='sent','Retentativa de e-mail funciona');
queueNotice($b,'revoked-unit','Não enviar WhatsApp revogado');query('UPDATE businesses SET whatsapp_consent=0 WHERE id=?',[$bid]);runDeliveries();check(!one("SELECT d.id FROM deliveries d JOIN notifications n ON n.id=d.notification_id WHERE n.dedup_key='revoked-unit' AND d.channel='whatsapp'"),'Autorização revogada é respeitada');
queueNotice($b,'expiry_'.$bid.'_2020-01-01_soon','Aviso antigo');runDeliveries();check(one("SELECT d.status FROM deliveries d JOIN notifications n ON n.id=d.notification_id WHERE n.dedup_key=?",['expiry_'.$bid.'_2020-01-01_soon'])['status']==='cancelled','Aviso de vencimento superado é cancelado');
query('UPDATE businesses SET paid_until=NULL,trial_until=NULL,manual_until=?,whatsapp_consent=1 WHERE id=?',[date('Y-m-d H:i:s',strtotime('-1 day')),$bid]);$b=one('SELECT * FROM businesses WHERE id=?',[$bid]);$oldKey='expiry_'.$bid.'_'.validUntil($b).'_soon';queueNotice($b,$oldKey,'Não enviar aviso prévio depois de vencer');prepareNotifications();prepareNotifications();$before=$calls;runDeliveries();check(one('SELECT d.status FROM deliveries d JOIN notifications n ON n.id=d.notification_id WHERE n.dedup_key=?',[$oldKey])['status']==='cancelled','Aviso prévio é descartado após expiração');$notice=expiryNotice($b);check(str_contains($notice['message'],'expirou em'),'Mensagem específica de expiração');check((int)one('SELECT COUNT(*) n FROM deliveries d JOIN notifications n ON n.id=d.notification_id WHERE n.dedup_key=? AND d.status=?',[$notice['key'],'sent'])['n']===2,'Expiração dispara nos dois canais configurados');$before=$calls;prepareNotifications();runDeliveries();check($calls===$before,'Expiração não é reenviada a cada execução');
$known='00020126580014br.gov.bcb.pix0136123e4567-e12b-12d1-a456-4266554400005204000053039865802BR5913Fulano de Tal6008BRASILIA62070503***6304';check(pixCrc($known)==='1D3D','CRC Pix validado com exemplo oficial do Banco Central');
require __DIR__.'/../server/metrics.php';putenv('ANALYTICS_ENABLED=true');$_SESSION=[];$_SERVER['HTTP_USER_AGENT']='Browser de teste';recordPortalMetric(['type'=>'visit']);recordPortalMetric(['type'=>'visit']);check(publicMetrics()['visits']===1,'Atualizações na mesma sessão não duplicam visitas');$_SESSION['metric_activity']=time()-1801;recordPortalMetric(['type'=>'visit']);check(publicMetrics()['visits']===2,'Inatividade de 30 minutos inicia nova visita');recordPortalMetric(['type'=>'search']);recordPortalMetric(['type'=>'search']);check((int)adminMetrics()['totals']['searches']===1,'Buscas rápidas são limitadas');check(adminMetrics()['today']['visits']===2,'Agregado diário acompanha visitas');$_SESSION=[];$_SERVER['HTTP_USER_AGENT']='Googlebot';recordPortalMetric(['type'=>'visit']);check(publicMetrics()['visits']===2,'Robôs identificados não contam');$_SERVER['HTTP_USER_AGENT']='Browser de teste';putenv('ANALYTICS_ENABLED=false');recordPortalMetric(['type'=>'visit']);check(publicMetrics()['visits']===2,'Coleta pausada não incrementa');
putenv('NOTIFICATION_MODE=manual');queueNotice($b,'manual-only','Mensagem apenas manual');$before=$calls;$result=runDeliveries();check($calls===$before&&$result['queued']===0,'Modo manual bloqueia provedores mesmo configurados');check(env('NOTIFICATIONS_ENABLED')==='false','Modo manual força automação desligada');
echo "$assertions verificações de pagamentos e automação passaram com provedores simulados.\n";
