const {test,expect}=require('@playwright/test');
test('Plano ativado substitui interesse na edição; capa cabe no cartão',async({page,browser})=>{
 const session=await (await page.request.get('/api/session')).json();const account=await (await page.request.post('/api/register',{headers:{'X-CSRF-Token':session.csrf},data:{name:'Cliente plano atual',email:'plano-atual@qa.local',password:'PlanoQA#2026!',consent:true}})).json();
 const headers={'X-CSRF-Token':account.csrf};expect((await page.request.post('/api/me/business',{headers,data:{name:'Plano atualizado teste',kind:'company',category_id:1,plan_id:4,interest_plan_id:4,description:'Atendimento de qualidade para toda a cidade de Sarzedo.',neighborhood:'Centro',phone:'31988887777',notification_channel:'email',publication_consent:true}})).ok()).toBeTruthy();const mine=await (await page.request.get('/api/me/business')).json();
 const admin=await browser.newContext({baseURL:'http://localhost:8091'});const sessionAdmin=await (await admin.request.get('/api/session')).json();const login=await (await admin.request.post('/api/login',{headers:{'X-CSRF-Token':sessionAdmin.csrf},data:{email:'admin@qa.local',password:'AdminQA#2026!'}})).json();expect((await admin.request.post('/api/admin/businesses/'+mine.id+'/activate',{headers:{'X-CSRF-Token':login.csrf},data:{plan_id:3,days:30,reason:'Ativação de teste do plano Premium'}})).ok()).toBeTruthy();
 expect((await admin.request.post('/api/admin/businesses/'+mine.id+'/approve',{headers:{'X-CSRF-Token':login.csrf},data:{reason:'Cadastro revisado para publicação'}})).ok()).toBeTruthy();
 await page.goto('/#!/painel');await expect(page.locator('.current-plan strong')).toHaveText('Premium');await expect(page.getByLabel('Plano de interesse')).toHaveCount(0);await page.getByRole('button',{name:'Salvar alterações'}).click();await expect(page.getByRole('status')).toContainText('Sua vitrine foi salva');const saved=await (await page.request.get('/api/me/business')).json();expect(saved.plan_id).toBe(3);expect(saved.interest_plan_id).toBe(4);
 await page.getByRole('button',{name:'Fotos e identidade'}).click();await page.getByLabel('Tipo de imagem').selectOption('cover');await page.locator('input[type=file]').setInputFiles('public/assets/icon-192.png');await expect(page.locator('.preview-cover')).toBeVisible();await page.goto('/');const card=page.locator('.business-card').filter({hasText:'Plano atualizado teste'});const image=card.locator('.card-image-link img');await expect(image).toHaveAttribute('src',/uploads/);for(const width of [1440,390]){await page.setViewportSize({width,height:900});expect(await image.evaluate(el=>{const a=el.getBoundingClientRect(),b=el.parentElement.getBoundingClientRect();return getComputedStyle(el).objectFit==='contain'&&Math.abs(a.width-b.width)<1&&Math.abs(a.height-b.height)<1;})).toBeTruthy();}await card.screenshot({path:'test-results/current-plan-card-mobile.png'});await admin.close();
});
