<?php
function adminUser(): array { $u=user(); if($u['role']!=='admin')fail('Acesso restrito à administração.',403);return $u; }
function audit(int $admin,?int $business,string $action,string $reason): void { query('INSERT INTO admin_audit(admin_id,business_id,action,reason,created_at) VALUES(?,?,?,?,?)',[$admin,$business,$action,$reason,date('Y-m-d H:i:s')]); }
function mapUrl(array $d): string { $url=urlField($d,'maps_url');if(!$url)return ''; $host=strtolower(parse_url($url,PHP_URL_HOST)??'');$path=parse_url($url,PHP_URL_PATH)??'';if(parse_url($url,PHP_URL_SCHEME)!=='https' || !($host==='maps.app.goo.gl'||$host==='maps.google.com'||$host==='maps.google.com.br'||(($host==='www.google.com'||$host==='www.google.com.br'||$host==='google.com')&&str_starts_with($path,'/maps'))||($host==='goo.gl'&&str_starts_with($path,'/maps'))))fail('Cole um link HTTPS do Google Maps, como https://maps.app.goo.gl/…');return $url; }
function sarzedoNeighborhoods(): array { return ['Cachoeira','Santa Rita','Santo Antônio','Quintas da Lagoa','Jardim Anchieta','Riacho da Mata','Brasília','Bairro Santa Rosa','Jardim Vera Cruz','Cinira de Freitas','Santa Rosa','São Pedro','Imaculada da Conceição','Centro','São Joaquim','Serra Azul','Imaculada Conceição','Masterville','Santa Mônica','Manoel Pinheiro','Vila Satélite']; }
function validatedHoursSchedule(mixed $input,string $existing=''): string {if($input===null)return $existing;if(!is_array($input))fail('Informe horários válidos.');$result=[];foreach(['mon','tue','wed','thu','fri','sat','sun'] as $day){$hours=$input[$day]??null;if(!$hours||(!($hours['open']??'')&&!($hours['close']??'')))continue;if(!is_array($hours)||!preg_match('/^(?:[01]\d|2[0-3]):[0-5]\d$/',(string)($hours['open']??''))||!preg_match('/^(?:[01]\d|2[0-3]):[0-5]\d$/',(string)($hours['close']??''))||$hours['open']>=$hours['close'])fail('Confira os horários de abertura e fechamento.');$result[$day]=['open'=>$hours['open'],'close'=>$hours['close']];}return $result?json_encode($result,JSON_UNESCAPED_UNICODE):'';}
function businessPromotions(int $id): array { $b=one('SELECT b.*,p.promotion_limit FROM businesses b JOIN plans p ON p.id=b.plan_id WHERE b.id=?',[$id]); if(!$b||!isLive($b))return [];return query('SELECT * FROM promotions WHERE business_id=? AND starts_at<=? AND expires_at>? ORDER BY created_at DESC LIMIT '.(int)$b['promotion_limit'],[$id,date('Y-m-d H:i:s'),date('Y-m-d H:i:s')])->fetchAll(); }
function queueNotice(array $b,string $key,string $message): void { if(one('SELECT id FROM notifications WHERE dedup_key=?',[$key]))return;try{query('INSERT INTO notifications(business_id,dedup_key,message,created_at) VALUES(?,?,?,?)',[$b['id'],$key,$message,date('Y-m-d H:i:s')]);}catch(PDOException $e){if(!one('SELECT id FROM notifications WHERE dedup_key=?',[$key]))throw $e;} }
function expiryNotice(array $b): ?array {
 $until=validUntil($b);if(isFreeBusiness($b)||!empty($b['is_demo'])||$b['status']==='suspended'||!$until||$until>date('Y-m-d H:i:s',strtotime('+3 days')))return null;
 $expired=$until<=date('Y-m-d H:i:s');$state=$expired?'expired':'soon';$message='Olá! A divulgação de '.$b['name'].' no Sarzedo por perto '.($expired?'expirou em ':'vence em ').date('d/m/Y H:i',strtotime($until)).'. '.($expired?(hasFreeDisplay($b)?'Sua vitrine aparece como Free até '.date('d/m/Y',strtotime(freeDisplayUntil($b))).', sem imagens, publicações e avaliações. ':'Sua vitrine está fora da busca. ').'Renove para recuperar os benefícios do seu plano. ':'Renove para manter sua vitrine disponível. ').'Gere o Pix no painel, pague e envie o comprovante para conferência em https://wa.me/5531987671102 . Acesse '.rtrim(env('APP_URL','http://localhost:8080'),'/').'/#!/painel para consultar seu Pix. Se já pagou, confira o status no painel.';
 return ['key'=>'expiry_'.$b['id'].'_'.$until.'_'.$state,'state'=>$state,'until'=>$until,'message'=>$message];
}
function renewalOverview(): array {
 $items=[];$counts=['soon'=>0,'expired'=>0];$integrations=integrationStatus();
 foreach(query('SELECT b.*,p.name plan FROM businesses b JOIN plans p ON p.id=b.plan_id WHERE b.is_demo=0')->fetchAll() as $b){$notice=expiryNotice($b);if(!$notice)continue;$counts[$notice['state']]++;$record=one('SELECT id,status FROM notifications WHERE dedup_key=?',[$notice['key']]);$deliveries=$record?query('SELECT channel,status,sent_at,last_error FROM deliveries WHERE notification_id=?',[$record['id']])->fetchAll():[];
 $channels=[];if(in_array($b['notification_channel'],['email','both'])&&$integrations['email'])$channels[]='E-mail';if(in_array($b['notification_channel'],['whatsapp','both'])&&$b['whatsapp_consent']&&$integrations['whatsapp'])$channels[]='WhatsApp';
 $items[]=['id'=>$b['id'],'name'=>$b['name'],'plan'=>$b['plan'],'state'=>$notice['state'],'until'=>$notice['until'],'message'=>$notice['message'],'manual_url'=>(manualNotifications()||$b['whatsapp_consent'])?'https://wa.me/55'.$b['phone'].'?text='.rawurlencode($notice['message']):null,'manual_done'=>$record&&$record['status']==='done','automatic'=>$integrations['automation']&&count($channels)>0,'channels'=>$channels,'deliveries'=>$deliveries];}
 usort($items,fn($a,$b)=>strcmp($a['until'],$b['until']));return ['counts'=>$counts,'items'=>$items];
}
function prepareNotifications(): void { foreach(query("SELECT * FROM businesses WHERE is_demo=0 AND status<>'suspended'")->fetchAll() as $b){if(isFreeBusiness($b))continue;$until=validUntil($b);$notice=expiryNotice($b);if($notice)queueNotice($b,$notice['key'],$notice['message']);if(!$until&&$b['activation_deadline']<=date('Y-m-d H:i:s',strtotime('+2 days')))queueNotice($b,'activation_'.$b['id'],'Olá! Seu cadastro no Sarzedo por perto está salvo. Ative a vitrine de '.$b['name'].' com Pix em '.env('APP_URL','http://localhost:8080').'/#!/painel.');} }

// Fixed query definitions only; page input never supplies SQL identifiers.
function adminRecords(string $type, int $page=1): array {
 $queries=[
  'advertisements'=>['a.*,b.name business_name','advertisements a JOIN businesses b ON b.id=a.business_id','1=1','a.id DESC'],
  'ad_orders'=>['o.*,b.name business_name,b.id business_id,a.id advertisement_id','ad_orders o JOIN businesses b ON b.id=o.business_id LEFT JOIN advertisements a ON a.order_id=o.id','1=1','o.id DESC'],
  'audit'=>['a.*,u.name admin_name','admin_audit a JOIN users u ON u.id=a.admin_id','1=1','a.id DESC'],
  'requests'=>['r.*,u.name,u.email','privacy_requests r JOIN users u ON u.id=r.user_id','1=1','r.id DESC'],
  'delivery_log'=>['d.*,n.message,b.name','deliveries d JOIN notifications n ON n.id=d.notification_id JOIN businesses b ON b.id=n.business_id','1=1','d.id DESC'],
  'notifications'=>['n.*,b.name,b.phone','notifications n JOIN businesses b ON b.id=n.business_id',"n.status='pending'".(manualNotifications()?'':' AND b.whatsapp_consent=1'),'n.id DESC'],
  'manual_pending'=>['p.*,b.id business_id,b.name business_name,COALESCE(m.txid,p.provider_id) txid,m.payment_id manual_payment_id','payments p JOIN subscriptions s ON s.id=p.subscription_id JOIN businesses b ON b.id=s.business_id LEFT JOIN manual_pix_payments m ON m.payment_id=p.id',"p.status IN ('PENDING','OVERDUE')",'p.due_date,p.id']
 ];
 if(!isset($queries[$type]))fail('Lista administrativa não encontrada.',404);
 [$select,$from,$where,$order]=$queries[$type];$total=(int)one("SELECT COUNT(*) n FROM $from WHERE $where")['n'];$pages=max(1,(int)ceil($total/25));$page=max(1,min($page,$pages));$offset=($page-1)*25;
 $items=query("SELECT $select FROM $from WHERE $where ORDER BY $order LIMIT 25 OFFSET $offset")->fetchAll();
 if($type==='notifications')foreach($items as &$item)$item['url']='https://wa.me/55'.$item['phone'].'?text='.rawurlencode($item['message']);
 if($type==='advertisements')foreach($items as &$item){$b=one('SELECT * FROM businesses WHERE id=?',[$item['business_id']]);$item['public_visible']=false;if(empty($item['image_url']))$item['visibility_reason']='Envie a imagem de 900 × 600 px.';elseif(empty($item['paid_at']))$item['visibility_reason']='Confirme o pagamento da publicidade.';elseif($item['status']!=='active')$item['visibility_reason']=$item['status']==='paused'?'Publicidade pausada.':'Publicidade ainda não foi ativada.';elseif(empty($item['starts_at'])||$item['starts_at']>date('Y-m-d H:i:s'))$item['visibility_reason']='O período de exibição ainda não começou.';elseif(empty($item['expires_at'])||$item['expires_at']<=date('Y-m-d H:i:s'))$item['visibility_reason']='Publicidade expirada.';elseif(!$b||$b['approval_status']!=='approved')$item['visibility_reason']='Aprove o cadastro do negócio para exibir a publicidade.';elseif($b['status']==='suspended')$item['visibility_reason']='O negócio está suspenso.';elseif(!isListed($b))$item['visibility_reason']='Ative ou renove a exibição do negócio.';else{$item['public_visible']=true;$item['visibility_reason']='Visível na página principal.';}}
 return ['items'=>$items,'page'=>$page,'pages'=>$pages,'total'=>$total,'page_size'=>25];
}

function featureRoutes(string $path,string $method): void {
 if($path==='/api/promotions' && $method==='GET') {
  $rows=query('SELECT p.*,b.name business_name,b.is_demo,b.plan_id,pl.priority FROM promotions p JOIN businesses b ON b.id=p.business_id JOIN plans pl ON pl.id=b.plan_id WHERE '.visibilitySql('b',false).' AND pl.promotion_limit>0 AND p.starts_at<=? AND p.expires_at>? ORDER BY pl.priority DESC,p.created_at DESC,p.id DESC',array_merge(visibilityParams(false),[date('Y-m-d H:i:s'),date('Y-m-d H:i:s')]))->fetchAll();$counts=[];$items=[];foreach($rows as $r){$counts[$r['business_id']]=($counts[$r['business_id']]??0)+1;$limit=(int)one('SELECT promotion_limit FROM plans WHERE id=?',[$r['plan_id']])['promotion_limit'];if($counts[$r['business_id']]<=$limit)$items[]=$r;}jsonResponse(array_slice($items,0,30));
 }
 if($path==='/api/me/business' && $method==='POST') {
  $u=user();$d=input();$b=one('SELECT * FROM businesses WHERE user_id=?',[$u['id']]);
  $category=(int)($d['category_id']??0);$plan=(int)($b['plan_id']??$d['plan_id']??4);$kind=field($d,'kind',1,20);
  if(!in_array($kind,['company','freelancer']))fail('Escolha empresa ou autônomo.');
  if(!one('SELECT id FROM categories WHERE id=?',[$category])||!one('SELECT id FROM plans WHERE id=?',[$plan]))fail('Escolha categoria e plano válidos.');
  $phoneInput=field($d,'phone',10,20);if(!preg_match('/^[0-9 ()+-]+$/',$phoneInput))fail('O WhatsApp deve conter somente números e formatação de telefone.');$phone=preg_replace('/\D/','',$phoneInput);if(!in_array(strlen($phone),[10,11]))fail('Informe WhatsApp com DDD, com 10 ou 11 dígitos.');
  $name=field($d,'name',2,150);$description=field($d,'description',20,3000);$purpose=field($d,'purpose',0,1000);$neighborhood=field($d,'neighborhood',2,100);if(!in_array($neighborhood,sarzedoNeighborhoods(),true)&&(!$b||$neighborhood!==$b['neighborhood']))fail('Escolha um bairro de Sarzedo na lista.');$publish=!empty($d['publish_address'])?1:0;$address=field($d,'address',$publish?5:0,255);$website=urlField($d,'website');$instagram=urlField($d,'instagram');$hours=field($d,'hours',0,255);$maps=mapUrl($d);$consent=manualNotifications()?(int)($b['whatsapp_consent']??0):(!empty($d['whatsapp_consent'])?1:0);
  // The billing-contact number remains private when no listing entitlement exists.
  if(!$b && empty($d['publication_consent']))fail('Confirme que autoriza a publicação dos dados da sua vitrine.');
  $facebook=urlField($d,'facebook_url');$tagline=field($d,'tagline',0,180);$services=field($d,'services',0,2000);$serviceArea=field($d,'service_area',0,255);$paymentMethods=field($d,'payment_methods',0,255);$interest=(int)($b?($b['interest_plan_id']??$b['plan_id']):($d['interest_plan_id']??$plan));if(!one('SELECT id FROM plans WHERE id=?',[$interest]))fail('Informe o plano de interesse.');$channel=manualNotifications()?($b['notification_channel']??'email'):(field($d,'notification_channel',0,20)?:'email');if(!in_array($channel,['email','whatsapp','both']))fail('Canal de aviso inválido.');if(!manualNotifications()&&in_array($channel,['whatsapp','both'])&&!$consent)fail('Autorize os avisos por WhatsApp ou selecione e-mail.');
  $reviewPreference=$b['reviews_opt_in']??1;if(array_key_exists('reviews_opt_in',$d)){if(!in_array($d['reviews_opt_in'],[true,false,0,1,'0','1'],true))fail('Preferência de avaliações inválida.');if(!isFreePlanId($b['plan_id']??$plan))$reviewPreference=!empty($d['reviews_opt_in'])?1:0;}
  $schedule=validatedHoursSchedule($d['hours_schedule']??null,$b['hours_schedule']??'');foreach(['delivery_available','home_service_available'] as $flag)if(array_key_exists($flag,$d)&&!in_array($d[$flag],[true,false,0,1,'0','1'],true))fail('Forma de atendimento inválida.');$delivery=array_key_exists('delivery_available',$d)?(int)(bool)$d['delivery_available']:(int)($b['delivery_available']??0);$homeService=array_key_exists('home_service_available',$d)?(int)(bool)$d['home_service_available']:(int)($b['home_service_available']??0);
  $consentAt=manualNotifications()?($b['consent_at']??null):($consent?date('Y-m-d H:i:s'):null);$values=[$name,$category,$description,$purpose,$neighborhood,$address,$phone,$website,$instagram,$hours,$kind,$maps,$publish,$consent,$consentAt,$facebook,$tagline,$services,$serviceArea,$paymentMethods,$interest,$channel,$reviewPreference];
  if($b){$values[]=$b['id'];query('UPDATE businesses SET name=?,category_id=?,description=?,purpose=?,neighborhood=?,address=?,phone=?,website=?,instagram=?,hours=?,kind=?,maps_url=?,publish_address=?,whatsapp_consent=?,consent_at=?,facebook_url=?,tagline=?,services=?,service_area=?,payment_methods=?,interest_plan_id=?,notification_channel=?,reviews_opt_in=? WHERE id=?',$values);}
  else{$s=settings();$now=date('Y-m-d H:i:s');$trial=(!isFreePlanId($plan)&&!empty($s['launch_start'])&&!empty($s['launch_end'])&&$s['launch_start']<=$now&&$s['launch_end']>$now)?$s['launch_end']:null;query('INSERT INTO businesses(name,category_id,description,purpose,neighborhood,address,phone,website,instagram,hours,kind,maps_url,publish_address,whatsapp_consent,consent_at,facebook_url,tagline,services,service_area,payment_methods,interest_plan_id,notification_channel,reviews_opt_in,user_id,plan_id,created_at,trial_until,activation_deadline) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',array_merge($values,[$u['id'],$plan,$now,$trial,isFreePlanId($plan)?null:date('Y-m-d H:i:s',strtotime('+5 days'))]));$b=one('SELECT * FROM businesses WHERE user_id=?',[$u['id']]);if($trial)queueNotice($b,'trial_'.$b['id'],'Olá! A vitrine de '.$b['name'].' está em degustação no Sarzedo por perto até '.date('d/m/Y',strtotime($trial)).'. Acesse seu painel para acompanhar.');}
  query('UPDATE businesses SET hours_schedule=?,delivery_available=?,home_service_available=?,updated_at=? WHERE id=?',[$schedule,$delivery,$homeService,date('Y-m-d H:i:s'),$b['id']]);
  jsonResponse(['ok'=>true]);
 }
 if($path==='/api/me/free-cover'&&$method==='POST'){$b=business();$d=input();$key=field($d,'key',0,40);if($key!==''&&$key!=='auto'&&!in_array($key,array_column(freeCoverLibrary(),'key'),true))fail('Escolha uma imagem da biblioteca do portal.');query('UPDATE businesses SET free_cover_key=? WHERE id=?',[$key,$b['id']]);jsonResponse(['ok'=>true]);}
 if($path==='/api/me/promotion-image'&&$method==='POST'){
  $b=business();if(!isLive($b))fail('Ative sua vitrine antes de enviar imagens.');$plan=one('SELECT promotion_limit FROM plans WHERE id=?',[$b['plan_id']]);if(!(int)$plan['promotion_limit'])fail('Seu plano não inclui promoções.');$f=$_FILES['photo']??null;if(!$f||$f['error']!==UPLOAD_ERR_OK||$f['size']>5*1024*1024)fail('Envie JPG, PNG ou WebP de até 5 MB.');$info=@getimagesize($f['tmp_name']);if(!$info||!in_array($info['mime'],['image/jpeg','image/png','image/webp'])||$info[0]*$info[1]>20000000)fail('Imagem inválida ou superior a 20 megapixels.');$source=@imagecreatefromstring(file_get_contents($f['tmp_name']));if(!$source)fail('Não foi possível abrir a imagem.');$w=900;$h=600;$target=imagecreatetruecolor($w,$h);imagefill($target,0,0,imagecolorallocate($target,255,255,255));$scale=min($w/$info[0],$h/$info[1]);$sw=(int)round($info[0]*$scale);$sh=(int)round($info[1]*$scale);imagecopyresampled($target,$source,(int)(($w-$sw)/2),(int)(($h-$sh)/2),0,0,$sw,$sh,$info[0],$info[1]);$url='/uploads/'.bin2hex(random_bytes(16)).'.jpg';if(!imagejpeg($target,ROOT.'/public'.$url,85))fail('Não foi possível salvar a imagem.',500);imagedestroy($source);imagedestroy($target);query('INSERT INTO promotion_images(business_id,url,created_at) VALUES(?,?,?)',[$b['id'],$url,date('Y-m-d H:i:s')]);jsonResponse(['url'=>$url],201);
 } if($path==='/api/me/promotions'&&$method==='POST'){
  $b=business();if(!isLive($b))fail('Ative sua vitrine antes de publicar promoções.');$d=input();$title=field($d,'title',3,100);$description=field($d,'description',10,1500);$rawPrice=$d['price']??null;if(!is_scalar($rawPrice)||!preg_match('/^\d{1,6}(?:\.\d{1,2})?$/',(string)$rawPrice))fail('Informe um preço numérico com até duas casas decimais.');$price=filter_var($rawPrice,FILTER_VALIDATE_FLOAT);if(isset($d['original_price'])&&$d['original_price']!==''&&(!is_scalar($d['original_price'])||!preg_match('/^\d{1,6}(?:\.\d{1,2})?$/',(string)$d['original_price'])))fail('Informe um preço anterior numérico com até duas casas decimais.');$original=isset($d['original_price'])&&$d['original_price']!==''?filter_var($d['original_price'],FILTER_VALIDATE_FLOAT):null;
  if($price===false||$price===null||$price<=0||$price>999999)fail('Informe um preço válido maior que zero.');if($original!==null&&($original===false||$original<=$price||$original>999999))fail('O preço anterior deve ser maior que o preço promocional.');
  $image=field($d,'image_url',1,500);$fixed=array_column(freeCoverLibrary(),'url');if(!one('SELECT id FROM promotion_images WHERE business_id=? AND url=?',[$b['id'],$image])&&!in_array($image,$fixed,true))fail('Envie uma imagem da promoção ou escolha uma imagem do portal.');
  $end=field($d,'expires_at',10,10);if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$end)||date('Y-m-d',strtotime($end))!==$end||$end<date('Y-m-d')||$end>date('Y-m-d',strtotime('+90 days')))fail('A promoção deve terminar entre hoje e os próximos 90 dias.');
  transaction(function()use($b,$title,$description,$price,$original,$image,$end){lockBusiness((int)$b['id']);$plan=one('SELECT * FROM plans WHERE id=?',[$b['plan_id']]);$count=one('SELECT COUNT(*) n FROM promotions WHERE business_id=? AND expires_at>?',[$b['id'],date('Y-m-d H:i:s')]);if($count['n']>=$plan['promotion_limit'])fail('Seu plano não permite mais promoções simultâneas.');query('INSERT INTO promotions(business_id,title,description,price_cents,original_price_cents,image_url,starts_at,expires_at,created_at) VALUES(?,?,?,?,?,?,?,?,?)',[$b['id'],$title,$description,(int)round($price*100),$original===null?null:(int)round($original*100),$image,date('Y-m-d H:i:s'),$end.' 23:59:59',date('Y-m-d H:i:s')]);});jsonResponse(['ok'=>true],201);
 }
 if(preg_match('#^/api/me/promotions/(\d+)$#',$path,$m)&&$method==='DELETE'){user();fail('Promoções publicadas só podem ser excluídas pelo administrador.',403);}
 if($path==='/api/me/export'&&$method==='GET'){$u=user();$b=one('SELECT * FROM businesses WHERE user_id=?',[$u['id']]);$result=['account'=>$u,'business'=>$b,'reviews'=>query('SELECT * FROM reviews WHERE user_id=?',[$u['id']])->fetchAll(),'privacy_requests'=>query('SELECT * FROM privacy_requests WHERE user_id=?',[$u['id']])->fetchAll()];if($b){foreach(['photos','posts','promotions','subscriptions']as$table)$result[$table]=query("SELECT * FROM $table WHERE business_id=?",[$b['id']])->fetchAll();$result['payments']=query('SELECT p.* FROM payments p JOIN subscriptions s ON s.id=p.subscription_id WHERE s.business_id=?',[$b['id']])->fetchAll();}jsonResponse($result);}
 if($path==='/api/me/privacy-request'&&$method==='POST'){$u=user();$d=input();$type=field($d,'request_type',1,40);if(!in_array($type,['access','correction','deletion','withdrawal']))fail('Escolha o tipo de solicitação.');if(one("SELECT id FROM privacy_requests WHERE user_id=? AND status='open' AND request_type=?",[$u['id'],$type]))fail('Você já possui uma solicitação deste tipo em análise.');query('INSERT INTO privacy_requests(user_id,request_type,details,created_at) VALUES(?,?,?,?)',[$u['id'],$type,field($d,'details',10,2000),date('Y-m-d H:i:s')]);jsonResponse(['ok'=>true],201);}
 if(!str_starts_with($path,'/api/admin/'))return;
 $admin=adminUser();
 if(preg_match('#^/api/admin/promotions/(\d+)$#',$path,$m)&&$method==='DELETE'){$p=one('SELECT * FROM promotions WHERE id=?',[$m[1]]);if(!$p)fail('Promoção não encontrada.',404);query('DELETE FROM promotions WHERE id=?',[$p['id']]);audit((int)$admin['id'],(int)$p['business_id'],'delete_promotion','Promoção #'.$p['id'].' excluída pelo administrador');jsonResponse(['ok'=>true]);}
 if(preg_match('#^/api/admin/records/([a-z_]+)$#',$path,$m)&&$method==='GET')jsonResponse(adminRecords($m[1],(int)($_GET['page']??1)));
 if($path==='/api/admin/google'&&$method==='POST'){saveGoogleSettings(input(),(int)$admin['id']);jsonResponse(googleSettings());}
 if($path==='/api/admin/asaas'&&$method==='POST'){saveAsaasSettings(input(),(int)$admin['id']);jsonResponse(asaasSettings());}
 if($path==='/api/admin/manual-pix'&&$method==='POST'){saveManualPix(input(),(int)$admin['id']);jsonResponse(manualPixSettings());}
 if(preg_match('#^/api/admin/payments/(\d+)/confirm-manual$#',$path,$m)&&$method==='POST'){confirmManualPix((int)$m[1],input(),(int)$admin['id']);jsonResponse(['ok'=>true]);}
 if(preg_match('#^/api/admin/plans/(\d+)$#',$path,$m)&&$method==='POST'){savePlanPricing((int)$m[1],input(),(int)$admin['id']);jsonResponse(['plans'=>planCatalog()]);}
 if(preg_match('#^/api/admin/businesses/(\d+)/renewal-done$#',$path,$m)&&$method==='POST'){
  transaction(function()use($m,$admin){lockBusiness((int)$m[1]);$b=one('SELECT * FROM businesses WHERE id=?',[$m[1]]);if(!$b)fail('Cadastro não encontrado.',404);$notice=expiryNotice($b);if(!$notice||(!manualNotifications()&&!$b['whatsapp_consent']))fail('Este cadastro não possui lembrete vigente autorizado para WhatsApp.');$d=input();if(($d['until']??'')!==$notice['until']||($d['state']??'')!==$notice['state'])fail('A validade mudou. Atualize o painel antes de registrar.',409);queueNotice($b,$notice['key'],$notice['message']);$n=one('SELECT id FROM notifications WHERE dedup_key=?',[$notice['key']]);if(one("SELECT id FROM deliveries WHERE notification_id=? AND status IN ('sending','uncertain')",[$n['id']]))fail('Há um envio em andamento ou com resultado incerto. Confira o histórico antes de concluir.',409);query("UPDATE notifications SET status='done' WHERE id=?",[$n['id']]);query("UPDATE deliveries SET status='cancelled',updated_at=? WHERE notification_id=? AND status IN ('pending','retry')",[date('Y-m-d H:i:s'),$n['id']]);audit((int)$admin['id'],(int)$b['id'],'renewal_manual_done','Administrador confirmou envio manual do lembrete '.$notice['state'].' até '.$notice['until']);});jsonResponse(['ok'=>true]);
 }
 if($path==='/api/admin/integrations'&&$method==='POST'){saveIntegrationConfig(input(),(int)$admin['id']);jsonResponse(integrationStatus());}
 if($path==='/api/admin/overview'&&$method==='GET'){
  $rows=query('SELECT b.*,u.name owner_name,u.email,p.name plan FROM businesses b JOIN users u ON u.id=b.user_id JOIN plans p ON p.id=b.plan_id ORDER BY b.id DESC')->fetchAll();$stats=['total'=>count($rows),'active'=>0,'trial'=>0,'pending'=>0];foreach($rows as &$b){$b['business_code']=businessCode((int)$b['id']);$b['visible']=isLive($b)&&isListed($b);$b['display_free']=isFreeBusiness($b)||hasFreeDisplay($b);$b['listed']=isListed($b);$b['suspended_by_expiry']=suspendedByExpiry($b);$b['display_until']=$b['display_free']?freeDisplayUntil($b):validUntil($b);$b['valid_until']=validUntil($b);$stats[$b['visible']?'active':'pending']++;if($b['trial_until']&&$b['trial_until']>date('Y-m-d H:i:s'))$stats['trial']++;}unset($b);
  $pages=[];foreach(['audit','requests','delivery_log','notifications','manual_pending','advertisements','ad_orders'] as $key)$pages[$key]=adminRecords($key,(int)($_GET[$key.'_page']??1));
  jsonResponse(['advertisements'=>$pages['advertisements']['items'],'ad_orders'=>$pages['ad_orders']['items'],'manual_pix'=>manualPixSettings(),'manual_pending'=>$pages['manual_pending']['items'],'pagination'=>array_map(fn($p)=>array_diff_key($p,['items'=>true]),$pages),'plans'=>planCatalog(),'businesses'=>$rows,'stats'=>$stats,'settings'=>settings(),'notifications'=>$pages['notifications']['items'],'requests'=>$pages['requests']['items'],'google_settings'=>googleSettings(),'asaas_settings'=>asaasSettings(),'traffic'=>adminMetrics(),'renewals'=>renewalOverview(),'finance'=>financeReport(),'delivery_log'=>$pages['delivery_log']['items'],'server_time'=>date('Y-m-d H:i:s'),'integrations'=>integrationStatus(),'audit'=>$pages['audit']['items']]);
 }
 if(preg_match('#^/api/admin/businesses/(\d+)$#',$path,$m)&&$method==='GET'){
  $b=one('SELECT b.*,u.name owner_name,u.email FROM businesses b JOIN users u ON u.id=b.user_id WHERE b.id=?',[$m[1]]);if(!$b)fail('Cadastro não encontrado.',404);foreach(['photos','posts','promotions','subscriptions']as$table)$b[$table]=query("SELECT * FROM $table WHERE business_id=?",[$b['id']])->fetchAll();$b['business_code']=businessCode((int)$b['id']);$b['payments']=query('SELECT p.*,m.txid,m.payment_id manual_payment_id FROM payments p JOIN subscriptions s ON s.id=p.subscription_id LEFT JOIN manual_pix_payments m ON m.payment_id=p.id WHERE s.business_id=? ORDER BY p.id DESC',[$b['id']])->fetchAll();$b['visible']=isLive($b)&&isListed($b);$b['display_free']=isFreeBusiness($b)||hasFreeDisplay($b);$b['listed']=isListed($b);$b['suspended_by_expiry']=suspendedByExpiry($b);$b['display_until']=$b['display_free']?freeDisplayUntil($b):validUntil($b);$b['valid_until']=validUntil($b);audit((int)$admin['id'],(int)$b['id'],'view','Consulta administrativa');jsonResponse($b);
 }
 if(preg_match('#^/api/admin/businesses/(\d+)/(activate|suspend|restore|approve|reject)$#',$path,$m)&&$method==='POST'){
  $d=input();$reason=field($d,'reason',5,500);$b=one('SELECT * FROM businesses WHERE id=?',[$m[1]]);if(!$b)fail('Cadastro não encontrado.',404);
  transaction(function()use($b,$d,$reason,$m,$admin){lockBusiness((int)$b['id']);if(in_array($m[2],['approve','reject'])){query('UPDATE businesses SET approval_status=? WHERE id=?',[$m[2]==='approve'?'approved':'rejected',$b['id']]);}elseif($m[2]==='activate'){$days=filter_var($d['days']??null,FILTER_VALIDATE_INT);$plan=one('SELECT * FROM plans WHERE id=?',[(int)($d['plan_id']??0)]);if($plan&&isFreePlanId($plan['id']))fail('O Free não exige ativação por prazo. Use retirar suspensão para restaurar um cadastro Free.');if(!$days||$days<1||$days>365||!$plan)fail('Informe plano e validade de 1 a 365 dias.');if(one('SELECT COUNT(*) n FROM photos WHERE business_id=?',[$b['id']])['n']>$plan['photo_limit'])fail('Este plano não comporta a galeria atual.');$until=date('Y-m-d H:i:s',strtotime('+'.$days.' days',max(time(),strtotime(validUntil($b))?:0)));query("UPDATE businesses SET status='active',manual_until=?,plan_id=? WHERE id=?",[$until,$plan['id'],$b['id']]);queueNotice($b,'manual_'.$b['id'].'_'.$until,'Olá! A vitrine de '.$b['name'].' no Sarzedo por perto foi ativada até '.date('d/m/Y',strtotime($until)).'.');}else query('UPDATE businesses SET status=? WHERE id=?',[$m[2]==='suspend'?'suspended':'pending',$b['id']]);audit((int)$admin['id'],(int)$b['id'],$m[2],$reason);});jsonResponse(['ok'=>true]);
 }
 if($path==='/api/admin/settings'&&$method==='POST'){
  $d=input();$start=field($d,'launch_start',0,19);$end=field($d,'launch_end',0,19);if(($start&&!$end)||(!$start&&$end))fail('Preencha início e fim da campanha.');foreach([$start,$end]as$date)if($date&&(!preg_match('/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/',$date)||date('Y-m-d H:i:s',strtotime($date))!==$date))fail('Informe uma data e hora válidas nos campos da campanha.');if($start&&$end<=$start)fail('O fim da campanha deve ser posterior ao início.');
  $email=field($d,'privacy_email',0,190);if($email&&!filter_var($email,FILTER_VALIDATE_EMAIL))fail('E-mail de privacidade inválido.');$adPrice=isset($d['advertising_price'])?priceInCents($d['advertising_price']):(int)(settings()['advertising_price_cents']??3500);$name=field($d,'controller_name',0,190);$phoneInput=field($d,'support_whatsapp',0,20);if($phoneInput&&!preg_match('/^[0-9 ()+-]+$/',$phoneInput))fail('O WhatsApp deve conter somente números.');$phone=preg_replace('/\D/','',$phoneInput);if($phone&&!in_array(strlen($phone),[10,11,12,13]))fail('Informe um WhatsApp válido com DDD.');$mapsKey=field($d,'maps_embed_key',0,100);if($mapsKey&&!preg_match('/^[A-Za-z0-9_-]{30,100}$/',$mapsKey))fail('Informe uma chave válida da Google Maps Embed API.');
  transaction(function()use($start,$end,$email,$name,$phone,$admin,$adPrice,$mapsKey){foreach(['launch_start'=>$start,'launch_end'=>$end,'privacy_email'=>$email,'controller_name'=>$name,'support_whatsapp'=>$phone,'advertising_price_cents'=>(string)$adPrice,'maps_embed_key'=>$mapsKey]as$k=>$v)query('UPDATE settings SET value=? WHERE setting_key=?',[$v,$k]);audit((int)$admin['id'],null,'settings','Atualização da campanha e canais de atendimento');});jsonResponse(['ok'=>true]);
 }
 if(preg_match('#^/api/admin/notifications/(\d+)/done$#',$path,$m)&&$method==='POST'){query("UPDATE notifications SET status='done' WHERE id=?",[$m[1]]);audit((int)$admin['id'],null,'notification_done','Registro de atendimento #'.$m[1]);jsonResponse(['ok'=>true]);}
 if(preg_match('#^/api/admin/privacy/(\d+)/close$#',$path,$m)&&$method==='POST'){$d=input();$notes=field($d,'notes',10,2000);query("UPDATE privacy_requests SET status='closed',resolution=?,resolved_at=? WHERE id=?",[$notes,date('Y-m-d H:i:s'),$m[1]]);audit((int)$admin['id'],null,'privacy_close','Solicitação #'.$m[1]);jsonResponse(['ok'=>true]);}
 fail('Rota administrativa não encontrada.',404);
}


