<?php
function financeReport(): array {
 $businesses=query('SELECT b.*,p.name interest_plan,p.price_cents interest_price FROM businesses b JOIN plans p ON p.id=COALESCE(b.interest_plan_id,b.plan_id) WHERE b.is_demo=0')->fetchAll();
 $prices=[];foreach(planCatalog() as $plan)$prices[$plan['id']]=$plan['price_cents'];
 $forecast=0;$activeMrr=0;$expired=[];$byPlan=[];foreach(query('SELECT * FROM plans ORDER BY id')->fetchAll()as$p)$byPlan[$p['id']]=['name'=>$p['name'],'count'=>0,'potential_cents'=>0];
 foreach($businesses as $b){$interest=$b['interest_plan_id']??$b['plan_id'];$b['interest_price']=$prices[$interest];$forecast+=(int)$b['interest_price'];$byPlan[$interest]['count']++;$byPlan[$interest]['potential_cents']+=(int)$b['interest_price'];if($b['paid_until']&&$b['paid_until']>date('Y-m-d H:i:s')&&$b['status']!=='suspended'&&one("SELECT p.id FROM payments p JOIN subscriptions s ON s.id=p.subscription_id WHERE s.business_id=? AND p.status IN ('RECEIVED','CONFIRMED') AND p.provider_id NOT LIKE 'demo_%' AND p.valid_until>?",[$b['id'],date('Y-m-d H:i:s')]))$activeMrr+=(int)one("SELECT COALESCE(s.amount_cents,p.amount_cents) amount FROM payments p JOIN subscriptions s ON s.id=p.subscription_id WHERE s.business_id=? AND p.status IN ('RECEIVED','CONFIRMED') AND p.provider_id NOT LIKE 'demo_%' AND p.valid_until>? ORDER BY p.valid_until DESC LIMIT 1",[$b['id'],date('Y-m-d H:i:s')])['amount'];if(validUntil($b)&&validUntil($b)<=date('Y-m-d H:i:s'))$expired[]=['id'=>$b['id'],'name'=>$b['name'],'until'=>validUntil($b),'phone'=>$b['phone']];}
 $receivedByPlan=[];foreach(query('SELECT id,name FROM plans ORDER BY priority,id')->fetchAll() as $plan)$receivedByPlan[$plan['id']]=['id'=>(int)$plan['id'],'name'=>$plan['name'],'received_cents'=>0,'refunded_cents'=>0,'payments'=>0];
 $months=[];for($i=11;$i>=0;$i--){$month=date('Y-m',strtotime('-'.$i.' months',strtotime(date('Y-m-01'))));$months[$month]=['month'=>$month,'label'=>substr($month,5,2).'/'.substr($month,0,4),'received_cents'=>0,'refunded_cents'=>0,'net_cents'=>0,'plans_received_cents'=>0,'ads_received_cents'=>0,'by_plan'=>$receivedByPlan];}
 $payments=query("SELECT p.*,s.plan_id billed_plan_id,b.id business_id,b.name business_name FROM payments p JOIN subscriptions s ON s.id=p.subscription_id JOIN businesses b ON b.id=s.business_id WHERE b.is_demo=0 AND p.provider_id NOT LIKE 'demo_%'")->fetchAll();
 $received=0;$refunded=0;$pending=0;$overdue=0;$debtors=[];$paidBusinesses=[];
 foreach($payments as$p){$amount=(int)$p['amount_cents'];if($p['paid_at']){$received+=$amount;$planId=(int)$p['billed_plan_id'];$receivedByPlan[$planId]['received_cents']+=$amount;$receivedByPlan[$planId]['payments']++;$month=substr($p['paid_at'],0,7);if(isset($months[$month])){$months[$month]['received_cents']+=$amount;$months[$month]['plans_received_cents']+=$amount;$months[$month]['by_plan'][$planId]['received_cents']+=$amount;$months[$month]['by_plan'][$planId]['payments']++;}$paidBusinesses[$p['business_id']]=true;}if($p['refunded_at']){$refunded+=$amount;$planId=(int)$p['billed_plan_id'];$receivedByPlan[$planId]['refunded_cents']+=$amount;$month=substr($p['refunded_at'],0,7);if(isset($months[$month])){$months[$month]['refunded_cents']+=$amount;$months[$month]['by_plan'][$planId]['refunded_cents']+=$amount;}}if(in_array($p['status'],['PENDING','OVERDUE'])){if($p['due_date']<date('Y-m-d')){$overdue+=$amount;$debtors[]=$p;}else $pending+=$amount;}}
 $adsReceived=0;foreach(query("SELECT a.monthly_amount_cents,a.paid_at FROM advertisements a JOIN businesses b ON b.id=a.business_id WHERE a.paid_at IS NOT NULL AND b.is_demo=0")->fetchAll() as $ad){$value=(int)$ad['monthly_amount_cents'];$adsReceived+=$value;$received+=$value;$month=substr($ad['paid_at'],0,7);if(isset($months[$month])){$months[$month]['received_cents']+=$value;$months[$month]['ads_received_cents']+=$value;}}
 foreach($months as &$m)$m['net_cents']=$m['received_cents']-$m['refunded_cents'];unset($m);
 return ['received_by_plan'=>array_values($receivedByPlan),'plans_received_cents'=>$received-$adsReceived,'ads_received_cents'=>$adsReceived,'captured'=>count($businesses),'potential_cents'=>$forecast,'active_mrr_cents'=>$activeMrr,'received_cents'=>$received,'refunded_cents'=>$refunded,'net_cents'=>$received-$refunded,'pending_cents'=>$pending,'overdue_cents'=>$overdue,'converted'=>count($paidBusinesses),'conversion_percent'=>count($businesses)?round(count($paidBusinesses)/count($businesses)*100,1):0,'by_plan'=>array_values($byPlan),'months'=>array_values($months),'debtors'=>$debtors,'expired'=>$expired,'note'=>'Receita potencial não é faturamento. Valores brutos, sem taxas do provedor. Dados de demonstração e ativações manuais não contam como pagamentos.'];
}
