<?php
function pixCrc(string $data): string {$crc=0xffff;for($i=0;$i<strlen($data);$i++){$crc^=ord($data[$i])<<8;for($j=0;$j<8;$j++)$crc=(($crc&0x8000)?($crc<<1)^0x1021:$crc<<1)&0xffff;}return strtoupper(str_pad(dechex($crc),4,'0',STR_PAD_LEFT));}
function pixField(string $id,string $value): string {if(strlen($value)>99)throw new RuntimeException('Campo Pix excedeu o limite.');return $id.str_pad((string)strlen($value),2,'0',STR_PAD_LEFT).$value;}
function pixPayload(string $key,string $name,string $city,int $amount,string $txid): string {$payload=pixField('00','01').pixField('26',pixField('00','br.gov.bcb.pix').pixField('01',$key)).pixField('52','0000').pixField('53','986').pixField('54',number_format($amount/100,2,'.','')).pixField('58','BR').pixField('59',$name).pixField('60',$city).pixField('62',pixField('05',$txid)).'6304';return $payload.pixCrc($payload);}
function manualPixSettings(): array {return ['enabled'=>env('PAYMENT_DRIVER')==='manual_pix','configured'=>(bool)(env('PIX_KEY')&&env('PIX_RECIPIENT')&&env('PIX_CITY')),'recipient'=>env('PIX_RECIPIENT'),'city'=>env('PIX_CITY')];}
function saveManualPix(array $d,int $admin): void {
 $bucket='pix_admin_'.$admin.'_'.(int)floor(time()/600);$blocked=transaction(function()use($bucket){$r=one('SELECT attempts FROM rate_limits WHERE bucket=?',[$bucket]);if($r&&$r['attempts']>=5)return true;if($r)query('UPDATE rate_limits SET attempts=attempts+1 WHERE bucket=?',[$bucket]);else query('INSERT INTO rate_limits VALUES(?,?,?)',[$bucket,1,time()+600]);return false;});if($blocked)fail('Muitas tentativas. Aguarde dez minutos para alterar o recebimento Pix.',429);
 $account=one('SELECT password_hash,role FROM users WHERE id=?',[$admin]);if(!$account||$account['role']!=='admin'||!password_verify((string)($d['admin_password']??''),$account['password_hash']))fail('Informe sua senha de administrador para alterar o recebimento Pix.',403);query('DELETE FROM rate_limits WHERE bucket=?',[$bucket]);
 if(env('DEPLOY_ENV')==='staging')fail('Recebimento real desabilitado na homologação. Use os testes isolados para simular pagamentos.',403);
 $file=integrationConfigPath();$lock=fopen($file.'.lock','c');if(!$lock||!flock($lock,LOCK_EX))fail('Não foi possível salvar.',500);
 try{$config=integrationConfig();$key=field($d,'key',0,77);if($key){if(!(filter_var($key,FILTER_VALIDATE_EMAIL)||preg_match('/^\+[1-9][0-9]{7,14}$/',$key)||preg_match('/^[0-9]{11}$|^[0-9]{14}$/',$key)||preg_match('/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i',$key)))fail('Informe uma chave Pix válida: e-mail, CPF/CNPJ sem pontuação, telefone internacional ou chave aleatória.');if(strlen($key)>77)fail('Chave Pix muito longa.');$config['PIX_KEY']=$key;}
 foreach(['recipient'=>['PIX_RECIPIENT',25],'city'=>['PIX_CITY',15]]as$input=>$target){$v=strtoupper(iconv('UTF-8','ASCII//TRANSLIT',field($d,$input,1,$target[1])));if(!preg_match('/^[A-Z0-9 .-]+$/',$v)||strlen($v)>$target[1])fail('Use nome e cidade sem símbolos, dentro do limite indicado.');$config[$target[0]]=$v;}
 if(!empty($d['enabled'])){if(empty($config['PIX_KEY'])&&!env('PIX_KEY'))fail('Cadastre sua chave Pix primeiro.');if(one("SELECT id FROM subscriptions WHERE status IN ('creating','pending','active') AND provider_id NOT LIKE 'demo_%' AND provider_id NOT LIKE 'manual_%'"))fail('Existem assinaturas de outro provedor. Concilie e cancele essas renovações antes de mudar.');$config['PAYMENT_DRIVER']='manual_pix';}elseif(env('PAYMENT_DRIVER')==='manual_pix')$config['PAYMENT_DRIVER']=env('APP_ENV','local')==='local'?'demo':'disabled';
 $tmp=tempnam(dirname($file),'pix-');chmod($tmp,0600);if(file_put_contents($tmp,json_encode($config,JSON_THROW_ON_ERROR),LOCK_EX)===false||!rename($tmp,$file)){@unlink($tmp);fail('Não foi possível salvar.',500);}chmod($file,0600);audit($admin,null,'manual_pix_settings','Configuração de recebimento Pix atualizada; chave omitida.');
 }finally{flock($lock,LOCK_UN);fclose($lock);}
}
function manualInvoice(array $s): array {
 if(!manualPixSettings()['configured'])fail('O administrador precisa configurar o recebimento Pix.',503);
 $p=transaction(function()use($s){lockBusiness((int)$s['business_id']);$pending=one("SELECT * FROM payments WHERE subscription_id=? AND status IN ('PENDING','OVERDUE') ORDER BY id DESC LIMIT 1",[$s['id']]);if($pending)return $pending;
 $b=one('SELECT * FROM businesses WHERE id=?',[$s['business_id']]);$paid=one("SELECT id FROM payments WHERE subscription_id=? AND status IN ('RECEIVED','CONFIRMED')",[$s['id']]);if($paid&&validUntil($b)>date('Y-m-d H:i:s',strtotime('+3 days')))return null;
 if($s['status']==='cancelled')fail('Renovação cancelada. Contrate um plano novamente.');$amount=(int)$s['amount_cents'];$provider='manual_pay_'.bin2hex(random_bytes(12));$due=max(date('Y-m-d'),substr(validUntil($b),0,10));query("INSERT INTO payments(subscription_id,provider_id,amount_cents,status,due_date) VALUES(?,?,?,'PENDING',?)",[$s['id'],$provider,$amount,$due]);$id=(int)db()->lastInsertId();$txid='S'.strtoupper(bin2hex(random_bytes(12)));$payload=pixPayload(env('PIX_KEY'),env('PIX_RECIPIENT'),env('PIX_CITY'),$amount,$txid);query('INSERT INTO manual_pix_payments(payment_id,payload,recipient_name,txid) VALUES(?,?,?,?)',[$id,$payload,env('PIX_RECIPIENT'),$txid]);return one('SELECT * FROM payments WHERE id=?',[$id]);});
 if(!$p)return ['manual'=>true,'message'=>'Período pago vigente. O Pix de renovação será disponibilizado três dias antes do vencimento.'];$details=one('SELECT * FROM manual_pix_payments WHERE payment_id=?',[$p['id']]);return ['manual'=>true,'payload'=>$details['payload'],'recipient'=>$details['recipient_name'],'amount'=>$p['amount_cents']/100,'payment'=>$p,'message'=>'Após pagar, aguarde a conferência do recebimento pelo administrador. Não pague o mesmo código duas vezes.'];
}
function prepareManualRenewals(): void {if(env('PAYMENT_DRIVER')!=='manual_pix'||!manualPixSettings()['configured'])return;foreach(query("SELECT * FROM subscriptions WHERE provider_id LIKE 'manual_%' AND status='active'")->fetchAll()as$s)manualInvoice($s);}
function confirmManualPix(int $id,array $d,int $admin): void {
 if(empty($d['checked']))fail('Confirme que verificou o crédito no extrato do PicPay.');$amount=priceInCents($d['amount']??'');$ref=strtoupper(field($d,'reference',10,100));if(!preg_match('/^[A-Z0-9-]+$/',$ref))fail('Informe o identificador da transação sem espaços.');$date=field($d,'paid_date',10,10);$parsed=DateTimeImmutable::createFromFormat('!Y-m-d',$date);if(!$parsed||$parsed->format('Y-m-d')!==$date||$date>date('Y-m-d'))fail('Informe a data real do recebimento.');
 transaction(function()use($id,$amount,$ref,$date,$admin){$p=one('SELECT p.*,s.business_id FROM payments p JOIN subscriptions s ON s.id=p.subscription_id WHERE p.id=?',[$id]);if(!$p)fail('Cobrança não encontrada.',404);lockBusiness((int)$p['business_id']);$p=one('SELECT * FROM payments WHERE id=?',[$id]);if(in_array($p['status'],['RECEIVED','CONFIRMED']))fail('Pagamento já confirmado.',409);if(!in_array($p['status'],['PENDING','OVERDUE']))fail('Cobrança não está pendente.',409);if($amount!==(int)$p['amount_cents'])fail('O valor recebido deve corresponder ao valor da cobrança. Confira a divergência antes de ativar.');query('UPDATE settings SET value=value WHERE setting_key=?',['support_whatsapp']);if(one('SELECT id FROM advertisements WHERE bank_reference=?',[$ref])||one('SELECT payment_id FROM manual_pix_payments WHERE bank_reference=?',[$ref]))fail('Este identificador já foi utilizado.',409);if(!one('SELECT payment_id FROM manual_pix_payments WHERE payment_id=?',[$id]))query('INSERT INTO manual_pix_payments(payment_id,payload,recipient_name,txid) VALUES(?,?,?,?)',[$id,'','REGISTRO ANTIGO','LEGACY'.$id]);query('UPDATE manual_pix_payments SET bank_reference=?,confirmed_by=?,confirmed_at=? WHERE payment_id=?',[$ref,$admin,date('Y-m-d H:i:s'),$id]);applyPayment(['id'=>$p['provider_id'],'value'=>$amount/100,'status'=>'RECEIVED','dueDate'=>$p['due_date'],'paymentDate'=>$date],true);audit($admin,null,'manual_pix_confirmed','Recebimento conferido no extrato; cobrança #'.$id.'; valor em centavos '.$amount.($p['provider_id']&&str_starts_with($p['provider_id'],'demo_')?'; cobrança antiga de demonstração conciliada manualmente':''));});
}
