<?php
declare(strict_types=1);
require_once __DIR__.'/bootstrap.php';
$path=parse_url($_SERVER['REQUEST_URI'],PHP_URL_PATH);
$origin=rtrim(env('APP_URL','https://guiasarzedo.com.br'),'/');
function seoEscape(mixed $value): string { return htmlspecialchars((string)$value,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8'); }
if($path==='/sitemap.xml'){
 header('Content-Type: application/xml; charset=utf-8');
 $rows=query('SELECT b.id FROM businesses b WHERE b.is_demo=0 AND '.visibilitySql('b').' ORDER BY b.id',visibilityParams())->fetchAll();
 echo '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">';
 echo '<url><loc>'.seoEscape($origin.'/').'</loc></url>';
 foreach($rows as $row)echo '<url><loc>'.seoEscape($origin.'/empresa/'.$row['id']).'</loc></url>';
 echo '</urlset>';exit;
}
if(!preg_match('#^/empresa/(\d+)$#',$path??'',$match)){http_response_code(404);exit;}
$id=(int)$match[1];
$raw=one('SELECT b.*,c.name category,p.name plan,p.priority,p.promotion_limit FROM businesses b JOIN categories c ON c.id=b.category_id JOIN plans p ON p.id=b.plan_id WHERE b.id=?',[$id]);
if(!$raw||!isListed($raw)||$raw['is_demo']){http_response_code(404);header('Content-Type: text/plain; charset=utf-8');echo 'Empresa não encontrada.';exit;}
$active=isLive($raw);$b=publicBusiness($raw);$now=date('Y-m-d H:i:s');
$offers=$active&&!$b['is_free']?query('SELECT title,description,price_cents,original_price_cents,image_url,expires_at FROM promotions WHERE business_id=? AND starts_at<=? AND expires_at>? ORDER BY id DESC LIMIT '.(int)$raw['promotion_limit'],[$id,$now,$now])->fetchAll():[];
$posts=$active&&!$b['is_free']?query('SELECT title,body,image_url,created_at FROM posts WHERE business_id=? ORDER BY id DESC LIMIT 10',[$id])->fetchAll():[];
$reviews=$b['reviews_enabled']?query('SELECT r.rating,r.comment,r.created_at,u.name FROM reviews r JOIN users u ON u.id=r.user_id WHERE r.business_id=? AND r.hidden_at IS NULL ORDER BY r.id DESC LIMIT 10',[$id])->fetchAll():[];
$ratingSummary=$b['reviews_enabled']?one('SELECT AVG(rating) rating,COUNT(*) count FROM reviews WHERE business_id=? AND hidden_at IS NULL',[$id]):null;
$rating=$ratingSummary&&(int)$ratingSummary['count']>0?round((float)$ratingSummary['rating'],1):null;
$canonical=$origin.'/empresa/'.$id;
$name=$b['name'];$description=mb_substr(trim(preg_replace('/\s+/u',' ',$b['description'])),0,155);
$image=$origin.($b['cover_url']?:'/assets/default.svg');
$businessSchema=['@context'=>'https://schema.org','@type'=>$b['kind']==='freelancer'?'ProfessionalService':'LocalBusiness','name'=>$name,'url'=>$canonical,'description'=>$description,'image'=>$image,'address'=>['@type'=>'PostalAddress','addressLocality'=>'Sarzedo','addressRegion'=>'MG','addressCountry'=>'BR']];
if($b['contact_available']&&$b['address'])$businessSchema['address']['streetAddress']=$b['address'];
if($b['contact_available']&&$b['phone'])$businessSchema['telephone']='+55'.$b['phone'];
if($rating!==null)$businessSchema['aggregateRating']=['@type'=>'AggregateRating','ratingValue'=>$rating,'ratingCount'=>(int)$ratingSummary['count']];
$schema=json_encode($businessSchema,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT);
header('Content-Type: text/html; charset=utf-8');header('X-Content-Type-Options: nosniff');
?><!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=seoEscape($name)?> em Sarzedo, MG | Guia Sarzedo</title><meta name="description" content="<?=seoEscape($description)?>"><link rel="canonical" href="<?=seoEscape($canonical)?>"><meta property="og:type" content="website"><meta property="og:title" content="<?=seoEscape($name)?> em Sarzedo"><meta property="og:description" content="<?=seoEscape($description)?>"><meta property="og:url" content="<?=seoEscape($canonical)?>"><meta property="og:image" content="<?=seoEscape($image)?>"><script type="application/ld+json"><?=$schema?></script><link rel="stylesheet" href="/seo.css"><script src="/seo.js" defer></script></head>
<body data-business-id="<?=$id?>"><header class="seo-header"><a class="seo-brand" href="/">Sarzedo <span>por perto</span></a><a href="/">Buscar mais empresas →</a></header><main class="seo-wrap"><nav class="seo-breadcrumb"><a href="/">Início</a> / <?=seoEscape($b['category'])?> / <?=seoEscape($name)?></nav><article class="seo-profile"><img class="seo-cover" src="<?=seoEscape($b['cover_url']?:'/assets/default.svg')?>" alt="Imagem de <?=seoEscape($name)?>"><div class="seo-intro"><small><?=seoEscape($b['category'])?> · <?=seoEscape($b['neighborhood'])?> · Sarzedo, MG</small><h1><?=seoEscape($name)?></h1><?php if($b['tagline']):?><p class="seo-tagline"><?=seoEscape($b['tagline'])?></p><?php endif;?><p><?=nl2br(seoEscape($b['description']))?></p><div class="seo-actions"><?php if($b['contact_available']&&$b['phone']):?><a class="seo-button" data-metric="whatsapp_click" href="https://wa.me/55<?=seoEscape($b['phone'])?>" target="_blank" rel="noopener noreferrer">Conversar no WhatsApp ↗</a><?php endif;?><?php if($b['contact_available']&&$b['maps_url']):?><a class="seo-button secondary" data-metric="map_click" href="<?=seoEscape($b['maps_url'])?>" target="_blank" rel="noopener noreferrer">Ver localização ↗</a><?php endif;?><a class="seo-button secondary" href="/#!/empresa/<?=$id?>">Ver perfil e avaliar →</a></div></div></article>
<div class="seo-columns"><div><section><h2>Sobre este negócio</h2><?php if($b['services']):?><h3>Produtos e serviços</h3><p><?=nl2br(seoEscape($b['services']))?></p><?php endif;?><?php if($b['service_area']):?><h3>Região atendida</h3><p><?=seoEscape($b['service_area'])?></p><?php endif;?><?php if($b['payment_methods']):?><h3>Formas de pagamento</h3><p><?=seoEscape($b['payment_methods'])?></p><?php endif;?></section><?php if($offers):?><section><h2>Ofertas atuais</h2><div class="seo-items"><?php foreach($offers as $offer):?><article class="seo-item"><?php if($offer['image_url']):?><img src="<?=seoEscape($offer['image_url'])?>" alt="<?=seoEscape($offer['title'])?>"><?php endif;?><div><h3><?=seoEscape($offer['title'])?></h3><p><?=seoEscape($offer['description'])?></p><strong>R$ <?=seoEscape(number_format($offer['price_cents']/100,2,',','.'))?></strong><small>Até <?=seoEscape(date('d/m/Y',strtotime($offer['expires_at'])))?></small></div></article><?php endforeach;?></div></section><?php endif;?><?php if($posts):?><section><h2>Novidades</h2><div class="seo-items"><?php foreach($posts as $post):?><article class="seo-item"><?php if($post['image_url']):?><a href="<?=seoEscape($post['image_url'])?>" target="_blank" rel="noopener noreferrer" aria-label="Ampliar imagem de <?=seoEscape($post['title'])?>"><img src="<?=seoEscape($post['image_url'])?>" alt="Imagem de <?=seoEscape($post['title'])?>"></a><?php endif;?><div><h3><?=seoEscape($post['title'])?></h3><p><?=nl2br(seoEscape($post['body']))?></p><small><?=seoEscape(date('d/m/Y',strtotime($post['created_at'])))?></small></div></article><?php endforeach;?></div></section><?php endif;?><?php if($b['reviews_enabled']):?><section><h2>Avaliações</h2><?php foreach($reviews as $review):?><article class="seo-review"><strong><?=seoEscape($review['name'])?></strong> <span><?=str_repeat('★',(int)$review['rating'])?></span><p><?=seoEscape($review['comment'])?></p></article><?php endforeach;?><a href="/#!/empresa/<?=$id?>">Entrar ou criar conta para avaliar →</a></section><?php endif;?></div><aside class="seo-aside"><h2>Informações úteis</h2><p><strong>Bairro</strong><br><?=seoEscape($b['neighborhood'])?></p><?php if($b['address']):?><p><strong>Endereço</strong><br><?=seoEscape($b['address'])?></p><?php endif;?><?php if($b['hours']):?><p><strong>Horário informado</strong><br><?=nl2br(seoEscape($b['hours']))?></p><?php endif;?><?php if($b['website']):?><p><a href="<?=seoEscape($b['website'])?>" target="_blank" rel="noopener noreferrer">Site oficial ↗</a></p><?php endif;?><?php if($b['instagram']):?><p><a href="<?=seoEscape($b['instagram'])?>" target="_blank" rel="noopener noreferrer">Instagram ↗</a></p><?php endif;?><?php if($b['facebook_url']):?><p><a href="<?=seoEscape($b['facebook_url'])?>" target="_blank" rel="noopener noreferrer">Facebook ↗</a></p><?php endif;?></aside></div></main><footer class="seo-footer">Guia Sarzedo · Encontre e valorize quem está por perto.</footer></body></html>
