CREATE TABLE IF NOT EXISTS portal_metric_totals (id INTEGER PRIMARY KEY, visits INTEGER NOT NULL DEFAULT 0, searches INTEGER NOT NULL DEFAULT 0, started_at DATETIME NOT NULL);
CREATE TABLE IF NOT EXISTS portal_metric_days (metric_date DATE PRIMARY KEY, visits INTEGER NOT NULL DEFAULT 0, searches INTEGER NOT NULL DEFAULT 0);
