ALTER TABLE businesses ADD COLUMN tagline VARCHAR(180) NOT NULL DEFAULT '';
ALTER TABLE businesses ADD COLUMN services VARCHAR(2000) NOT NULL DEFAULT '';
ALTER TABLE businesses ADD COLUMN service_area VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE businesses ADD COLUMN payment_methods VARCHAR(255) NOT NULL DEFAULT '';
